# Generated by Django 5.2.1 on 2025-06-03 05:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchSigningJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partially Completed')], default='pending', max_length=20)),
                ('total_files', models.PositiveIntegerField(default=0)),
                ('processed_files', models.PositiveIntegerField(default=0)),
                ('successful_files', models.PositiveIntegerField(default=0)),
                ('failed_files', models.PositiveIntegerField(default=0)),
                ('save_location', models.CharField(blank=True, max_length=500, null=True)),
                ('naming_convention', models.CharField(default='signed_{original_name}', max_length=100)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_signing_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Batch Signing Job',
                'verbose_name_plural': 'Batch Signing Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PDFSigningTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('original_file_path', models.CharField(max_length=500)),
                ('signed_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('signed_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('pages_count', models.PositiveIntegerField(default=0)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('batch_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='pdf_signature.batchsigningjob')),
            ],
            options={
                'verbose_name': 'PDF Signing Task',
                'verbose_name_plural': 'PDF Signing Tasks',
                'ordering': ['original_filename'],
            },
        ),
    ]
